import type { Locale } from '../domain/cv-schema'

export const labels = {
  es: {
    education: 'Formación',
    experience: 'Experiencia laboral',
    courses: 'Cursos destacados',
    contactData: 'Datos de contacto',
    professionalSummary: 'Resumen profesional',
    coreExpertise: 'Competencias clave',
    coreExpertiseFootnote:
      'Antigüedad calculada con la fecha de inicio indicada y las experiencias del CV: TypeScript/React/testing solo cuentan donde figuran en tecnologías; JavaScript abarca desde el primer rol frontend hasta hoy.',
    languages: 'Idiomas',
    technologies: 'Tecnologías y herramientas',
    project: 'Proyecto',
    client: 'Cliente',
    projectsAtCompany: 'Proyectos en la misma empresa',
    addExperience: 'Añadir experiencia',
    addEducation: 'Añadir formación',
    addCourse: 'Añadir curso',
    printPdf: 'Descargar CV (PDF)',
    printPdfVector: 'Imprimir',
    documentTitle: 'CV',
    manageExperiences: 'Gestionar experiencias',
    manageEducation: 'Gestionar formación',
    manageCourses: 'Gestionar cursos',
    edit: 'Editar',
    save: 'Guardar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    comingSoon: 'Próximamente',
    duration: 'Duración',
    linkedInQr: 'LinkedIn QR',
    changeLanguageToSpanish: 'Cambiar idioma a español',
    changeLanguageToEnglish: 'Cambiar idioma a inglés',
    sendEmailTo: 'Enviar correo a',
    openLinkedIn: 'Abrir LinkedIn',
    mainContent: 'Contenido principal',
    sidebarContent: 'Contenido lateral',
  },
  en: {
    education: 'Education',
    experience: 'Work experience',
    courses: 'Highlighted courses',
    contactData: 'Contact details',
    professionalSummary: 'Professional summary',
    coreExpertise: 'Core expertise',
    coreExpertiseFootnote:
      'Tenure is computed from the stated frontend start date and dated roles: TypeScript, React, and testing only count where those tools appear in the CV; the JavaScript line runs from the first frontend role through today.',
    languages: 'Languages',
    technologies: 'Technologies and tools',
    project: 'Project',
    client: 'Client',
    projectsAtCompany: 'Projects at the same company',
    addExperience: 'Add experience',
    addEducation: 'Add education',
    addCourse: 'Add course',
    printPdf: 'Download CV (PDF)',
    printPdfVector: 'Print',
    documentTitle: 'CV',
    manageExperiences: 'Manage experiences',
    manageEducation: 'Manage education',
    manageCourses: 'Manage courses',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    comingSoon: 'Coming soon',
    duration: 'Length',
    linkedInQr: 'LinkedIn QR',
    changeLanguageToSpanish: 'Switch language to Spanish',
    changeLanguageToEnglish: 'Switch language to English',
    sendEmailTo: 'Send email to',
    openLinkedIn: 'Open LinkedIn',
    mainContent: 'Main content',
    sidebarContent: 'Sidebar content',
  },
} as const

export function t(locale: Locale) {
  return labels[locale]
}
